mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views


app_name = 'polls'

urlpatterns = [
	url(r'^$', views.LoginFormView.as_view(), name='login'),

	url(r'^register/$', views.UserFormView.as_view(), name='reg'),

	url(r'^questions/$', views.IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),

    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible  # only if you need to support Python 2
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
    	return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

@python_2_unicode_compatible  # only if you need to support Python 2
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta: 
		model = User
		fields = ['username', 'email', 'password']



class LoginForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta: 
		model = User
		fields = ['username', 'password']

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm, LoginForm


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
                """
                Return the last five published questions (not including those set to be
                published in the future).
                """
                return Question.objects.filter(
                    pub_date__lte=timezone.now()
                ).order_by('-pub_date')[:5]
 

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class UserFormView(View):
    form_class = UserForm
    template_name = 'polls/registration_form.html'

    #display blank form using get
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    #process the form data using post
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            #cleaned and normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #return user object if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('polls:index')


        return render(request, self.template_name, {'form': form})


class LoginFormView(View):
    form_class = LoginForm
    template_name = 'polls/login_form.html'

    #display blank form using get
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    #process the form data using post
    def post(self, request):
        #cleaned and normalized data
        username = request.POST['username']
        password = request.POST['password']

        #return user object if credentials are correct
        user = authenticate(username=username, password=password)

        if user:
            print("Not none")

            if user.is_active:
                login(request, user)
                return redirect('polls:index')

        return redirect('polls:login')

polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
<br>
<a href="{% url 'polls:index'%}">back to question list</a>
</form>

polls/templates/polls/form-template.html
{% for field in form %}
	<div class="form-group">
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if latest_question_list %}

    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/login_form.html
{% block title %}Login{% endblock %}

{% block body %} 
<div class="container-fluid">

	<div class="row"> 

		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'polls/form-template.html' %}
						<div class="form-group"> 
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success" href="{% url 'polls:index' %}">
									Submit
								</button>
							</div>
						</div>
					</form>
				</div>
				<a type="submit" class="btn btn-success" href="{% url 'polls:reg' %}"> register </a>
			</div>
		</div>
	</div>
</div>

{% endblock %}

polls/templates/polls/registration_form.html
{% block title %}Register{% endblock %}

{% block body %} 
<div class="container-fluid">

	<div class="row"> 

		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'polls/form-template.html' %}
						<div class="form-group"> 
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success" href="{% url 'polls:index' %}">
									Submit
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

polls/templates/polls/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>